# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection) or
# paste cURL into the file and request will be converted to HTTP Request format.
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

POST http://localhost:8080/members
Accept: application/json
Content-Type: application/json

{
  "id":"test",
  "password":"test",
  "name":"test",
  "loginUrl":"test"
}

> {%
client.test("[멤버 생성] Success Test", function() {
    client.assert(response.status === 200, "Response status is not 200");
    client.assert(response.body['no'] !== 0, "no is not generated")
})
%}

###

GET http://localhost:8080/members

> {%
client.test("[멤버 조회] Success Test", function() {
    client.assert(response.status === 200, "Response status is not 200");
    client.assert(response.body.length !== 0, "Member not found")
})
%}

###

GET http://localhost:8080/members/1

> {%
client.test("[멤버 단건 조회] Success Test", function() {
    client.assert(response.status === 200, "Response status is not 200");
    client.assert(response.body.length !== 0, "Member not found")
    client.assert(response.body['no'] === 1, "Member not found")
})
%}

###

PUT http://localhost:8080/members/1
Accept: application/json
Content-Type: application/json

{
  "id":"test2",
  "password":"test2",
  "name":"test2",
  "loginUrl":"test2"
}


> {%
client.test("[멤버 수정] Success Test", function() {
    client.assert(response.status === 200, "Response status is not 200");
    client.assert(response.body.length !== 0, "Member not found")
    client.assert(response.body['id'] === 'test2', "Member not found")
})
%}


###

DELETE http://localhost:8080/members/1

> {%
client.test("[멤버 삭제] Success Test", function() {
    client.assert(response.status === 200, "Response status is not 200");
})
%}

###